// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace MoreMovementGameplayTags
{
	PRONEMOVEMENTMODE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Prone);
	PRONEMOVEMENTMODE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	PRONEMOVEMENTMODE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_Crouch);
	PRONEMOVEMENTMODE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_Prone);
	PRONEMOVEMENTMODE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_Sprint);
	PRONEMOVEMENTMODE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_Walk);
	PRONEMOVEMENTMODE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_Jump);
	PRONEMOVEMENTMODE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Sprint);
};
